services:
  podcast-gen:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: podcast-gen
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    volumes:
      - ./static:/app/static
