version: '3.8'

services:
  api:
    build: .
    container_name: podcast-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
    env_file:
      - .env